// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Player struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	ShortName   string  `json:"shortName"`
	Email       *string `json:"email"`
	Elo         float64 `json:"elo"`
	Experiennce int     `json:"experiennce"`
}
