// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GameRequest struct {
	Limit    *int `json:"limit"`
	Offset   *int `json:"offset"`
	WinnerID *int `json:"winnerId"`
	LoserID  *int `json:"loserId"`
}

type Player struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	ShortName   string  `json:"shortName"`
	Email       *string `json:"email"`
	Elo         float64 `json:"elo"`
	Experiennce int     `json:"experiennce"`
}

type Tournament struct {
	ID       int    `json:"id"`
	Date     string `json:"date"`
	Location string `json:"location"`
	Name     string `json:"name"`
	Open     bool   `json:"open"`
}
